### ISSUE TITLE
Comparing array elements doesn't work.

### ISSUE THREAD

**Issue by KrzysztofSzewczyk** [maviek/sapphire#10]
Code:
```
var a[3]
var b[3]

a = "abc"
b = "cba"

if a[0] == b[0]
    putchar 49
    asm
        end
putchar 48

```
Expected output: 0 (a != c)
Actual output: 1

**Comment by maviek** [comment]
```python
var a[3]
var b[3]

a = "abc"
b = "cba"

var x
var y
x = a[0]
y = b[0]

if x == y
    putchar 49
    asm
        end
putchar 48
```
this works. idk why expr inside if doesn't work ¯\_(ツ)_/¯

**Comment by maviek** [comment]
![image](https://user-images.githubusercontent.com/29343327/47869018-18150180-de06-11e8-94df-f966cc664aa5.png)

**Comment by maviek** [comment]
![image](https://user-images.githubusercontent.com/29343327/47869281-dd5f9900-de06-11e8-84c8-0b3bd8b29a40.png)
fixed!
